<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
    <summary errors="1" failures="0" finished="true" name="Test Run: 20" tests="0" total_time="Finished in: 0.02 secs."/>
    <test location="C:\Users\Alejandro Molinar\Documents\Programming\PythonP\Beginning\Proof1\PersonList.py" status="error" test="PersonList" time="0">
        <stdout/>
        <stderr>
            <![CDATA[Traceback (most recent call last):
  File "C:\Users\Alejandro Molinar\.p2\pool\plugins\org.python.pydev.core_8.3.0.202104101217\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:\Users/Alejandro Molinar/Documents/Programming/PythonP/Beginning/Proof1\PersonList.py", line 39, in <module>
    myList.showPerson();
  File "C:\Users/Alejandro Molinar/Documents/Programming/PythonP/Beginning/Proof1\PersonList.py", line 24, in showPerson
    print(per);
  File "C:\Users/Alejandro Molinar/Documents/Programming/PythonP/Beginning/Proof1\PersonList.py", line 14, in __str__
    return "{}{}{}{}", format(self.fName, self.uName, self.gender, self.age);
TypeError: format expected at most 2 arguments, got 4
ERROR: Module: PersonList could not be imported (file: C:\Users\Alejandro Molinar\Documents\Programming\PythonP\Beginning\Proof1\PersonList.py).
]]>
        </stderr>
    </test>
    <launch mode="run">
        <launch_memento>
            <![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Beginning PersonList.py (1)"/>
]]>
        </launch_memento>
    </launch>
</pydev-testsuite>
